**1. Importação de bibliotecas e carregamento do arquivo no Google Colab:**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 2017.csv to 2017.csv

In [ ]:
df = pd.read_csv('2017.csv')

**2. Análise inicial de dados**

In [ ]:
df.head()

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Dew Point,DHI,DNI,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Wind Speed,Unnamed: 18
0,2017,1,1,0,0,-0.6,0,0,0,-2.6,0,0,0,86.29,152.92,0.12,1003,1.7,NaN
1,2017,1,1,0,15,-0.6,0,0,0,-2.6,0,0,0,86.29,150.22,0.12,1003,1.7,NaN
2,2017,1,1,0,30,-0.6,0,0,0,-2.6,0,0,0,86.29,147.43,0.12,1003,1.7,NaN
3,2017,1,1,0,45,-0.6,0,0,0,-2.7,0,0,0,85.54,144.60,0.12,1003,1.6,NaN
4,2017,1,1,1,0,-0.7,0,0,0,-2.7,0,0,0,86.17,141.71,0.12,1003,1.6,NaN

In [ ]:
df.shape

(35040, 19)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                35040 non-null  int64
 1   Month               35040 non-null  int64
 2   Day                 35040 non-null  int64
 3   Hour                35040 non-null  int64
 4   Minute              35040 non-null  int64
 5   Temperature         35040 non-null  float64
 6   Clearsky DHI        35040 non-null  int64
 7   Clearsky DNI        35040 non-null  int64
 8   Clearsky GHI        35040 non-null  int64
 9   Dew Point           35040 non-null  float64
 10  DHI                 35040 non-null  int64
 11  DNI                 35040 non-null  int64
 12  GHI                 35040 non-null  int64
 13  Relative Humidity   35040 non-null  float64
 14  Solar Zenith Angle  35040 non-null  float64
 15  Surface Albedo      35040 non-null  float64
 16  Pressure            35040 non-null  int64
 17  Wind Speed          35040 non-null  float64
 18  Unnamed: 18         0 non-null      float64
dtypes: float64(7), int64(12)
memory usage: 5.1 MB

In [ ]:
df.describe()

,Year,Month,Day,Hour,Minute,Temperature,Clearsky DHI,Clearsky DNI,Clearsky GHI,Dew Point,DHI,DNI,GHI,Relative Humidity,Solar Zenith Angle,Surface Albedo,Pressure,Wind Speed,Unnamed: 18
count,35040.0,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,35040.000000,0.0
mean,2017.0,6.526027,15.720548,11.500000,22.500000,17.598550,54.705251,316.586301,238.681079,10.000605,59.325342,234.925400,201.060674,65.853913,89.672410,0.138274,993.971090,2.811116,NaN
std,0.0,3.447901,8.796373,6.922285,16.770749,8.713459,67.206394,359.823802,312.994277,5.086833,86.020009,337.229851,294.243230,21.195051,37.114298,0.012801,5.422638,1.439266,NaN
min,2017.0,1.000000,1.000000,0.000000,0.000000,-4.000000,0.000000,0.000000,0.000000,-5.300000,0.000000,0.000000,0.000000,14.960000,14.620000,0.120000,977.000000,0.200000,NaN
25%,2017.0,4.000000,8.000000,5.750000,11.250000,11.300000,0.000000,0.000000,0.000000,7.200000,0.000000,0.000000,0.000000,50.037500,60.350000,0.130000,990.000000,1.700000,NaN
50%,2017.0,7.000000,16.000000,11.500000,22.500000,16.800000,0.000000,0.000000,0.000000,10.500000,0.000000,0.000000,0.000000,68.120000,89.300000,0.140000,993.000000,2.500000,NaN
75%,2017.0,10.000000,23.000000,17.250000,33.750000,23.800000,105.000000,705.000000,475.000000,13.800000,103.000000,530.000000,371.000000,84.370000,119.130000,0.150000,998.000000,3.700000,NaN
max,2017.0,12.000000,31.000000,23.000000,45.000000,41.400000,415.000000,990.000000,1026.000000,21.900000,488.000000,990.000000,1026.000000,100.000000,165.340000,0.160000,1010.000000,11.300000,NaN

**3. Limpeza dos dados (Data cleaning) 🧹**

In [ ]:
df.isnull().sum()

Year                      0
Month                     0
Day                       0
Hour                      0
Minute                    0
Temperature               0
Clearsky DHI              0
Clearsky DNI              0
Clearsky GHI              0
Dew Point                 0
DHI                       0
DNI                       0
GHI                       0
Relative Humidity         0
Solar Zenith Angle        0
Surface Albedo            0
Pressure                  0
Wind Speed                0
Unnamed: 18           35040
dtype: int64

In [ ]:
df.drop(columns=['Unnamed: 18'], inplace=True)

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Year, Month, Day, Hour, Minute, Temperature, Clearsky DHI, Clearsky DNI, Clearsky GHI, Dew Point, DHI, DNI, GHI, Relative Humidity, Solar Zenith Angle, Surface Albedo, Pressure, Wind Speed]
Index: []

In [ ]:
for col in df.columns:
    duplicados = df[col].duplicated().sum()
    print(f"Coluna '{col}' tem {duplicados} valores duplicados.")

Coluna 'Year' tem 35039 valores duplicados.
Coluna 'Month' tem 35028 valores duplicados.
Coluna 'Day' tem 35009 valores duplicados.
Coluna 'Hour' tem 35016 valores duplicados.
Coluna 'Minute' tem 35036 valores duplicados.
Coluna 'Temperature' tem 34587 valores duplicados.
Coluna 'Clearsky DHI' tem 34686 valores duplicados.
Coluna 'Clearsky DNI' tem 34052 valores duplicados.
Coluna 'Clearsky GHI' tem 34018 valores duplicados.
Coluna 'Dew Point' tem 34773 valores duplicados.
Coluna 'DHI' tem 34561 valores duplicados.
Coluna 'DNI' tem 34052 valores duplicados.
Coluna 'GHI' tem 34018 valores duplicados.
Coluna 'Relative Humidity' tem 27309 valores duplicados.
Coluna 'Solar Zenith Angle' tem 22021 valores duplicados.
Coluna 'Surface Albedo' tem 35035 valores duplicados.
Coluna 'Pressure' tem 35006 valores duplicados.
Coluna 'Wind Speed' tem 34933 valores duplicados.

In [ ]:
for col in df.columns:
    valores_duplicados = df[col][df[col].duplicated()]
    print(f"\nColuna '{col}':")
    print(valores_duplicados.unique())

Coluna 'Year':
[2017]

Coluna 'Month':
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Coluna 'Day':
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]

Coluna 'Hour':
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Coluna 'Minute':
[ 0 15 30 45]

Coluna 'Temperature':
[-0.6 -0.7 -0.8 -0.9 -1.  -1.1 -1.2  7.3  7.   6.7  4.3  3.   2.6  2.5
  2.2  2.   1.8  1.7  1.5  1.3  1.2  1.   0.9  0.8  0.7  0.5  0.4  0.3
  0.2  0.1  0.  -0.1 -0.2  3.6  5.5  5.9  6.8  7.2  8.2  8.   7.9  7.7
  7.5  6.5  6.1  5.7  5.2  4.9  4.7  4.   3.8  3.4  2.9  2.7  2.3  2.1
  1.9  2.8  3.3  7.1 11.5 11.2 10.7  9.9  9.4  6.9  6.6  6.3  6.2  6.
  5.6  5.4  5.3  5.1  5.   4.8  8.9 10.5 10.9 11.4 11.7 11.8 11.6 11.1
 10.4  9.2  9.5  9.6  9.7  9.8 10.  10.1 10.3 10.8 11.  12.4 12.5 12.6
 12.7 13.  14.5 14.6 14.7 14.4 14.2 14.  13.6 13.3 13.2 12.8 12.9 13.1
 13.5 13.8 14.1 14.3 13.9 13.7 12.3 12.  10.6  8.4  7.6  6.4  4.4  4.1
  3.1  1.1  0.6 -3.2 -3.3 -3.4 -3.1 -3.  -2.9 -2.8 -2.7 -2.6 -2.4 -2.
 -1.8  1.4  1.6 -0.3 -1.5 -2.2 -2.5 -3.6 -3.8 -3.9 -4.  -3.7 -3.5 -2.3
 -1.4 -0.4  2.4  3.2  5.8  4.5  4.2  4.6  3.9  7.4  8.3  8.6  9.3 10.2
  9.   8.7  8.5  8.1  8.8  9.1  3.7  3.5  7.8 11.9 12.1 12.2 11.3 13.4
 -0.5 -1.3 -1.6 -1.7 -1.9 -2.1 15.  14.9 14.8 15.1 15.3 15.4 15.2 15.8
 15.9 15.7 15.5 15.6 17.6 17.4 17.3 17.2 16.4 16.5 16.7 16.9 17.  17.5
 17.1 16.8 16.6 16.1 17.7 16.2 16.3 16.  18.1 18.2 17.9 17.8 18.  18.7
 18.6 18.5 18.4 18.3 19.2 19.4 19.3 19.  18.9 21.1 21.  20.9 20.8 20.7
 20.5 19.1 19.6 20.  20.3 20.6 20.4 20.2 19.8 20.1 18.8 19.9 19.7 22.
 21.9 21.7 21.5 19.5 21.2 21.4 23.3 23.6 23.5 23.4 23.1 22.7 22.5 21.8
 22.3 22.8 22.9 22.6 22.2 22.1 22.4 24.7 24.6 24.5 24.3 24.2 24.  23.8
 23.  23.2 25.8 26.  25.9 25.7 25.5 25.4 25.3 25.1 24.8 24.4 26.1 25.6
 24.9 21.3 23.9 24.1 25.2 25.  21.6 23.7 26.2 26.3 26.4 27.9 27.8 27.5
 27.2 26.7 27.7 28.  29.2 29.3 28.7 28.5 28.3 27.1 26.5 26.9 28.8 28.9
 29.  29.1 27.6 27.4 26.6 26.8 27.  27.3 28.6 31.7 31.6 31.5 31.4 31.3
 30.7 30.2 29.9 30.5 30.9 31.1 31.2 31.  30.8 30.4 29.7 28.1 28.2 29.4
 29.5 29.6 29.8 28.4 30.1 30.6 30.3 30.  32.1 32.2 32.  31.9 31.8 33.4
 33.3 33.2 33.1 32.7 32.5 32.9 34.8 34.9 34.7 34.6 34.5 34.  32.8 32.4
 32.3 32.6 33.6 34.1 34.3 35.5 35.6 35.4 35.3 35.1 33.8 33.7 33.9 34.2
 34.4 33.5 33.  35.  35.2 37.  37.2 37.1 36.8 36.7 36.5 36.4 35.7 36.1
 36.9 39.2 39.3 39.1 38.9 38.8 38.6 38.4 35.9 36.2 37.4 37.7 38.1 40.4
 40.2 40.1 39.9 39.5 39.  38.7 37.9 39.8 40.3 41.3 41.2 41.  40.8 40.6
 36.6 36.3 36.  35.8 37.3 37.5 37.6 37.8 38.  38.2 38.5 38.3 39.4 39.7
 39.6]

Coluna 'Clearsky DHI':
[  0  79  80  78  76  70  67  37  28  17  56  60  63  65  83  84  81  72
  48  19  31  42  51  64  69  77  95  96  93  91  90  85  59  43  68  73
  82  86  92 102 101 103 100  89  58  35  18  97 106 114 123 117  98  74
  88 118  99 122 121 120 139 126  94  21  38 105 127 130 147 144 145 135
 134  20  36  87 110 104 107 111 109  75  50 112 116  44  27 174 155 129
 128 108  57  49  33  54  61  53  71 119  52  47  24  14  66  32  23  16
  34  46  55  39  41 140 141 115 124 136 137  22  62  30  40  11  25  45
 125 150 154 143   8 153 172 192 191 157 148  13  15  29 132 131 133 138
 113 146 156 171 177 151 152  26 158 160 163 164 165 162 183 166 159  12
   9 186 190 195 196 194 197 193 185 175 180 187 189 184 142  10 161 168
 169 170 207 210 181 149 220 229 227 222 217 213 179 176 231 240 246 248
 249 221 208 212 205 167 173 188 201 228 242 315 223 202 214 272 270 268
 265 256 224 203 182 178 198 215 209 232 247 236 234 225 219 204 206 243
 235 218 251 230 200   7 199 216   6 226 245 244 311   5 237 211 253 302
 301 283 279 262 241 252 250 264 259 254 233 257 266 255 299 293 267 258
 285 288 289 278 275 273 282 280 322 287 239 357 271 323 356 375 374 334
 310   3 238 261 281 260 292   2 274 291 297 321 325 387 349 277   4 263
 290 295 313 307]

Coluna 'Clearsky DNI':
[  0 892 856 806 852 882 883 881 702 822 817 810 780 255 727 748 783 787
 768 685 634 565 705 719 720 694 675 342 542 760 775 762 766 713 477 442
 297 579 726 706 696 483 403 521 609 646 697 717 776 786 794 801 803 704
 674 548 754 761 771 779 781 678 576  22 143 431 520 632 638 637 707 690
 665 629 562 274 636 825 829 819 785 755 598 464 103 256 327 561 764 890
 880 868 836 821 591 659 854 888 918 917 893 811 782 747 653 499  97 217
 407 594 686 734 792 814 808 800 750 681 618 314 358 729 774 784 796 805
 746 652 610 364 630 684 703 770 736 716 627 577 379 680 714 700 600 534
 492 225 331 504 725 765 778 830 798 708 676 595 538 385 753 790 807 799
 772 752 663 501 371 146 264 363 743 804 826 846 851 849 841 833 749 642
 590 444 240 721 788 848 861 896 901 903 818 732 644 400 484 658 834 954
 953 950 912 875 855 735 687 253 487 566 842 870 886 812 763 662 554 427
 224  17 218 475 515 581 624 625 639 651 667 669 660 656 649 580 563 469
 242 210 282 525 550 587 592 571 547 405 288  26 439 537 635 671 728 860
 867 885 900 858 582 429 305 179 476 698 813 832 873 895 920 916 914 847
 835 552 349 249 539 948 943 938 907 845 791 757 507 391 545 699 824 862
 899 923 930 933 926 913 884 874 795 769 739 695 777 767 733 673 323 180
 533 689 944 952 970 958 828 756 641 559 295 239 406 910 964 966 931 922
 897 742 691 628 443 359 626 877 894 887 831 793 740 611 544 353 418 509
 710 737 723 661 616 517 451 147 334 532 715 744 730 145 404 467 655 693
 478 336 237 187 378 527 711 751 820 738 712 490  49 456 668 816 631 555
 510 455 291  18  37  93 162 557 731 724 360 268 259 401 452 575 647 722
 621 606 588 567 480 447 352 294 153 412 597 682 599 623 650 648 486 366
  48 414 519 593 622 672 677 556 502 450 350  96 619 827 844 878 921 932
 905 871 869 759 518 244 936 946 955 983 951 879 758 645 296 251 961 968
 988 987 984 709 417 866 906 904 919 454 344 207 377 718 802 915 928 924
 940 962 911 617 535 426 437 553 859 945 965 974 978 977 458 316 196 345
 540 701 797 864 857 654 605 551 380 277 155 466 526 560 602 679 741 585
 428 372 231 148   9  86 463 488 530 603 692 573 498 393 261  77 421 241
 127  19 245 416 485 809 124  60 329 508 823 633 495 284 126 339 503 789
 872 815 612 494  78 138 212 410 546 640 569 536  59  82 133 270 346 541
 583 589 584 578 425 369 328 169   1  12  46 293 332 367 398 436 460 402
 415 435 496 438 216  92   5 522 471 390 280 232 185 128  73   3 247 643
 683 853 843 574 325 238 205 891 292 204 461 389 167 865 898 934 941 935
 163 889 929 927  36  53 312 745 368  57 191 773 850 840 208 303 434 491
 614 613 601 524 322 229 604 664 313 132  33  88 223 289 317 411 838 670
 221  20 154 343 399 666  68  15 383 493 596 568 433  80 186 285 370 608
 279 105  28  66 130 337 615 570 543 472 287  81  56 141 228 307 512 159
  61  31 131 468 549 392 271 201 949 975 473 388 189 620 657 902  64 311
 529 357 514 505 267 956 976 971 967 942 959 320 151  79 248 500 947 937
  62 286 381 688 382   4 104 175 396 513 376  44  90 220 837 315 457 394
 341  10  55 121 373 420 462 528  98 586 262 173  99 123 523 101 481 909
 384 564   6 149 234  14 184 432   2  52 607 474 362  58 365 150 839 459
 235 283 908 925 107 448 158 304 506  38 361  87 166 257 160 193 876  41
 423 489 419  29 109 200 310 182  63 446 413 176 120 863 319 102  24 100
 190 276 243 188 116  65  25  39 230 273 354 300 236  11 335 511 422 326
 309  94 558 197  72  69 424 330 144 351 254 168 219 531 441 395 290 134
 198 222 142 213  89  27 306 298 156 324 408 226 318 281  23 111 164 117
 386 195  71 215 397 497 112 260 272 252 113  13  34 516 348  74 129 356
 449 440 269 299 214 137 957 174 246 453 572  40 136 939 347  51 465 211
  91  83 265  30 110 203 157  54  42 140 333 250 387 266 340  76 479  45
 301 470 139 338  50 114 375 308  70 302 202   8  85 374 170 161 409 135
  84 275 125 108 152 258 430 119 177 278 445 263 206  75  32 194  67 321
 227 122  16 482 171 199 165  43 118  21   7 233 192 178 183  47 106 115
 209 181  35  95]

Coluna 'Clearsky GHI':
[   0  511  444 ...  250 1003  641]

Coluna 'Dew Point':
[-2.6 -2.7 -2.8 -2.4 -2.3 -2.1 -1.6 -1.8 -2.5 -2.2 -2.  -1.9 -1.5 -1.7
 -3.1 -1.2 -0.9 -0.7 -0.6 -0.5 -0.4 -0.3 -0.1  0.   0.1  0.7  1.2  2.4
  3.8  4.5  4.9  5.   5.2  4.7  5.1  4.8  5.5  6.1  6.6  6.9  7.2  7.3
  7.4  7.6  7.7  7.9  8.3  8.5  8.7  9.2  9.5  9.7  9.9 10.3 10.9 11.3
 11.7 11.8 11.5 11.1 10.7 10.2 10.5 10.6 11.4 12.  11.2  9.3  8.8  8.
  7.1  7.   8.6  8.2  6.5  5.7  5.3  4.3  3.  -3.2 -3.6 -3.9 -4.2 -4.3
 -4.1 -4.  -3.8 -3.5 -3.7 -4.4 -4.7 -4.9 -5.  -4.5 -5.3 -5.2 -1.1 -1.
 -0.2  0.3  0.2  0.4  1.   1.4  2.   3.4  5.9  5.6  4.2  3.1  2.9  2.8
  2.6  2.5  2.3  0.9  3.3  3.7  3.9  4.   4.6  6.2  6.7  8.4  9.   5.8
  4.4  2.1  2.7  1.3  0.6 -0.8  1.1  0.5  1.7  6.3  8.9  9.4 10.   7.5
  6.   9.6  9.8 10.4 10.8  9.1 10.1 11.   8.1  6.8  7.8  6.4  4.1  3.6
  3.2  1.5  1.6  1.8  0.8 -1.3 -1.4  3.5 -3.  -3.3 -3.4  1.9  2.2 -2.9
 -4.8 11.9 12.1 12.3 12.2 12.5  5.4 11.6 12.9 12.4 12.7 13.6 13.2 12.6
 13.  13.1 12.8 13.4 13.3 13.5 13.7 14.1 14.6 14.7 15.1 15.  14.2 13.8
 14.  13.9 15.4 14.9 14.8 14.4 14.3 16.3 15.8 15.6 15.3 14.5 15.5 16.1
 15.2 17.1 16.9 16.  16.4 15.9 15.7 16.7 17.2 16.8 16.6 16.5 16.2 17.
 17.8 18.3 18.4 18.2 18.1 17.9 17.4 17.3 17.5 18.7 18.9 19.  18.8 17.6
 18.5 17.7 19.4 19.3 18.6 18.  19.2 19.8 20.3 20.6 21.  21.3 21.5 21.7
 21.9 20.  19.1 19.5 19.6 19.7 19.9 20.1 20.2 20.5 20.4 20.7 20.8 20.9]

Coluna 'DHI':
[  0  79  80  78  76  70  67   9  21  36 103  60  63  65  83  84  81  72
  48  77  95  96  93  91  54  37  19 151 176  51  20  75  59  45  31  12
  22  43 199 211 179  23  16  10   5   7  13  11  26  15  18  25  39   6
   4   8  27 136 173 220  40  38  90  24  30  44  73 104 205 212 213 110
 107  68  33  74 111 167 122  42 175 166 132  64   3  17  66  35 116   2
  29  56  88 109 218 223 221 178 155 134 112  28 123 207 150 189 120  57
  14  52  71  69  61  53  49  32 187  41  99 164 144 208 222 200 152  34
  82  94 105  92  55  50  85  86  62  58 170 183 197 228 247 172 156 106
   1  46 204 206 216 217 147 140  87 235 198 177 193 194 128  47 130 138
 160 171 232 240 114  89 117 142 115 124  98 227 141 163 191 168 108 162
 145 196 246 270 202 169 174 245 225 127 230 268 265 248 214 184 131 113
 121 146 158 165 271 161 241 180 125 186 195 283 192 203 185 137 102 190
 188 159 148 129 101 100 118 242  97 157 312 201 249 126 139 273 295 317
 215 209 252 237 234 309 251 310 308 226 224 258 229 307 304 289 231 256
 243 276 287 275 272 262 233 210 244 278 291 320 294 284 282 277 236 254
 280 279 296 293 274 305 135 119 238 267 181 133 149 153 286 313 333 318
 335 302 299 324 319 314 292 154 306 260 255 371 321 322 311 326 334 373
 143 367 364 360 325 290 182 361 342 343 353 348 375 355 266 315 300 253
 351 344 257 297 370 328 316 219 389 374 303 358 250 346 363 331 384 359
 382 356 281 259 323 329 390 394 357 239 327 350 338 339 376 377 415 399
 411 407 369 403 336 261 354 366 332 387 429 447 416 301 263 379 378 365
 420 352 288 421 437 431 330 422 362 349 395 424 381 383 264 298 428 432
 435 340 440 458 398 404 347 372 397 414 445 409 401 391 413 461 433 457
 388 341 285 408 402 471 392 337 345 393 425 452 470 465 451 426 462 474
 406 476 380 405 467 443 466 434 480 446 482 449 473 455 456 436 412 418
 400 419 463 442 448 450 396 410 385 475 479 427 438 444 486 269 454 453
 441 439 423 368]

Coluna 'DNI':
[  0 892 856 806 852 882 883 881 702 822 817 810  66  67  25 175 167 801
 794 143  34   9   2  22 215  80  43  21   8  47  88   6  38 591 836 888
 918 917 893 868 782 499   4 848 861 896 901 903 262 658 720 766 834 920
 954 927 926 912 890 875 812 584 391  31  56 346 228 162 129 192 145  24
  17  51 126 114 139 113 103 109  48   1 179  18 644 125 854 873 895 916
 266 118 140 788 953 950 948 938 845 748 824 862 899 923 930 933 913 907
 884 874 739 594  35   3   5   7  54  52 285 813 781 706 562 180 244 826
 944 952 970 958 756 685 146 819 847 910 932 964 966 931 922 911 841 559
 626 786 807 867 877 897 894 831 793 768 740 705  19  63  57 124 142 160
  36  29  68 187  23  10  40 106  78 188 182  49  92  39  14  28 207 127
 189 296 265  81  45 665 689 699 716 721 272 316 621 410 153  77 412  26
 632 204 653 550 401 224 133  33 128 651 622 655 672 677 673 671 663 682
 636 556 390 350 163  61  96 379 619 749 844 858 878 887 921 905 885 871
 869 851 804 787 715 661 533 625 695 750 829 936 955 983 951 943 855 707
 450 961 968 988 987 984 832 799 759 709 217 225 919 717 502 833 900 915
 928 924 946 962 879 535 426 553 638 755 945 965 974 978 977 791 703 641
 540 610 797 864 886 493 866 846 785 763  59  60 110  83 144  20  16  65
 170  71 261 199  79 582 241  30  13  53 185 177 230 280 247 816 238  12
 120  27 155 292 906 131  46 418 210 141 211 178  94 633 298 196 190  37
  89 191 554 565 583 240 195  87  72  50 135 332 339 403 405 398 507 490
 447 421 362 323  73  15  75  58 349 857 395 386 310 263 324 424 406 295
 253 209  41  64  11  91 164 123 288 461 563 669 767 802 789 780 754 733
 597 456 567 752 779 835 865 898 934 941 935 820 757 117 714 762 818 929
 872 557 297 312 414 495 256 216 334  97 365 368 400 270 148  76 115 747
 281 274 305 337 232 371 355  90 290 394 251  42  86 236 442 628 656 680
 738 229 152 161 252 301 568 433 494 545 627 659 157 112  70  93 186 271
 136 104 279 589 769 223 790 255 156  98 278 159 427 478 624 648 718 731
 773 795 798 777 723 599 101 336 524 674 697 711 259 267 269  69 575 753
 825 850 940 949 975 914 675 611 291 366 138 313 827 808 327 119 201 377
 527 620 727 821 880 902 800 587 522 166 311 423 512 760 889 904 830 811
 645 593 345 221 338 347 448 419 397 399 361 202 407 417 595 660 719 860
 956 976 971 967 942 434 302 667 758 823 959 539 151 248 500 649 774 849
 947 870 840 724 618 544 451  62 286 459 615 687 776 838 842 843 828 814
 444 174 197 737 299 322 294 194 306 541 222 220 344 438 640 683 484 529
 488 510 476 560 309 372 382 374 282  84 646 200 735 815 837 730 694 666
 601 184 293 353 455 356 431 700 289  32 212 102  44 219 367 538 577 771
 764 712 463 317 284 481 909 796 684 596 137 384 469 751 805 693 657 231
 351 173 245 364 578 647 765 792 722 515 235 333 432 425 440 443 437 472
 454 435 642 604 574 474  55 506 242 784 744 287 130 937 154 726 650 360
 283 623 908 925 318 214 193 679 385 258 107 183 537 713 853 487 453 165
 276 690 330 580 308 509  95 181 122 409 150 300 686 778 783 378 681 608
 564 536 630 775 803 704 676 526 466 411 100 471 588 662 876 839 268 430
 859 809 746 698 635 483 254 415 340 569 498 413 307 176 863 516 729 585
 534 132 668 408 602  85  82 108 468 116 227 149 548 158 532 517 492 497
 436 404 381 373 358 701 249 614 696 891 741 631 518 439 341 320 566 172
 728 772 331 168  99 321 380 393 441 239 357 273 428 692 467 277 376 613
 637 770 213 710 612 528 496 742 734 243 629 708 552 486 607 383 449 206
 121 218 105 237 171 359 335 329 546 670 732 328 233 464 416 558 617 314
 134 388 260 250 420 315 530 326 203 586 375 520 342 246 264 639 652 234
 736 458 957 678 573 743 319 561 501 348 592 205 745 446 939 688 304 605
 465 504 275 363 521 761 392 198 691 389 452 600 387 325 208 226 505 542
 503 111  74 551 457 470 634 654 480 609 598 519 429 511 547 370 482 485
 460 477 303 570 343 725 576 616 579 508 491 606 523 473 479 525 572 590
 555 257 643 513 402 422 147 396 549 445 543 664 581 531 169 489 571 462
 603 352 369 514 354 475]

Coluna 'GHI':
[  0 511 444 ... 850 641 488]

Coluna 'Relative Humidity':
[86.29 86.08 86.25 ... 85.04 88.82 98.86]

Coluna 'Solar Zenith Angle':
[ 61.39 164.53 160.16 ... 164.98 162.09 155.5 ]

Coluna 'Surface Albedo':
[0.12 0.13 0.14 0.15 0.16]

Coluna 'Pressure':
[1003 1002 1001 1000  999  998  997  996  995  994  993  992  991  990
  989  988  987  986  985  984  983  982  981  980  979  978  977 1004
 1005 1006 1007 1008 1009 1010]

Coluna 'Wind Speed':
[ 1.7  1.6  1.8  1.9  2.   2.1  2.6  2.4  2.3  2.2  1.4  1.5  1.3  0.8
  0.7  0.6  0.5  0.9  1.   1.1  1.2  2.5  2.7  3.6  3.5  3.4  3.3  3.2
  3.1  3.   2.9  3.8  3.9  3.7  4.6  4.9  5.   5.2  5.3  6.4  6.3  6.2
  6.1  6.   5.9  5.8  6.5  5.4  5.5  5.7  6.9  7.2  7.5  7.6  7.7  7.9
  8.   8.3  8.7  8.8  8.9  9.2 11.3 11.2 11.1 10.8 10.4  9.8  9.5  9.1
  7.3  7.   6.7  4.3  4.1  4.   2.8  5.1  5.6  4.8  4.7  4.5  4.4  4.2
  6.6  0.4  7.1  7.4  6.8  0.3  0.2  7.8  8.1  8.2  8.4  8.5  9.   8.6]

In [ ]:
df.dtypes

Year                    int64
Month                   int64
Day                     int64
Hour                    int64
Minute                  int64
Temperature           float64
Clearsky DHI            int64
Clearsky DNI            int64
Clearsky GHI            int64
Dew Point             float64
DHI                     int64
DNI                     int64
GHI                     int64
Relative Humidity     float64
Solar Zenith Angle    float64
Surface Albedo        float64
Pressure                int64
Wind Speed            float64
dtype: object

In [ ]:
df['time'] = pd.to_datetime(df[['Year', 'Month', 'Day', 'Hour', 'Minute']])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35040 entries, 0 to 35039
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                35040 non-null  int64
 1   Month               35040 non-null  int64
 2   Day                 35040 non-null  int64
 3   Hour                35040 non-null  int64
 4   Minute              35040 non-null  int64
 5   Temperature         35040 non-null  float64
 6   Clearsky DHI        35040 non-null  int64
 7   Clearsky DNI        35040 non-null  int64
 8   Clearsky GHI        35040 non-null  int64
 9   Dew Point           35040 non-null  float64
 10  DHI                 35040 non-null  int64
 11  DNI                 35040 non-null  int64
 12  GHI                 35040 non-null  int64
 13  Relative Humidity   35040 non-null  float64
 14  Solar Zenith Angle  35040 non-null  float64
 15  Surface Albedo      35040 non-null  float64
 16  Pressure            35040 non-null  int64
 17  Wind Speed          35040 non-null  float64
 18  time                35040 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(6), int64(12)
memory usage: 5.1 MB

In [ ]:
def get_season_north(date):
    day = date.day
    month = date.month

    if (month == 12 and day >= 21) or (1 <= month <= 2) or (month == 3 and day < 20):
        return 'Winter'
    elif (month == 3 and day >= 20) or (4 <= month <= 5) or (month == 6 and day < 21):
        return 'Spring'
    elif (month == 6 and day >= 21) or (7 <= month <= 8) or (month == 9 and day < 22):
        return 'Summer'
    elif (month == 9 and day >= 22) or (10 <= month <= 11) or (month == 12 and day < 21):
        return 'Autumn'

In [ ]:
df['season'] = df['time'].apply(get_season_north)